version: "3"
services:
  server:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: population-management-api
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ../../:/app
    depends_on:
      - database
    environment:
      DATABASE_URI: mongodb://database:27017/population-manager
      DATABASE_URI_TEST: mongodb://database:27017/sms-manager-test
      TRAVIS: ${TRAVIS}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}

  database:
    image: mongo
    container_name: mongo-db
    restart: always
